version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql

  adminer:      
    image: adminer
    restart: always
    ports:
    - 1234:8080